### ISSUE TITLE
Commands & Automoderation Tab in the dashboard error

### ISSUE THREAD

**Issue by 6despise** [onesoft-sudo/sudobot-dashboard#11]
![image](https://github.com/user-attachments/assets/920811eb-5e74-4b5d-9418-c91569279fec)
![image](https://github.com/user-attachments/assets/88ff0690-d21b-4b9a-baf4-537c7c6c2fb1)

**Comment by virtual-designer** [comment]
Hello, I think I have answered this to you in our Discord server. I'll be closing this issue. 
If you have any further questions, please create a new issue or re-open this.
